import type {
  AuditLog,
  CompatibilityStatus,
  ModelFile,
  ModelStatus,
  RegistryModel,
} from "@/modules/model-registry/types";

let idCounter = 100;

export function generateId(prefix: string): string {
  idCounter += 1;
  return `${prefix}-${idCounter}`;
}

export function formatDateTime(iso: string | null): string {
  if (!iso) return "—";
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(iso));
}

export function formatNumber(n: number): string {
  return new Intl.NumberFormat("en-US").format(n);
}

export function formatRelativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  if (days === 0) return "Today";
  if (days === 1) return "Yesterday";
  if (days < 30) return `${days} days ago`;
  return formatDateTime(iso);
}

export const statusStyles: Record<
  ModelStatus,
  { bg: string; text: string; dot: string }
> = {
  Draft: { bg: "bg-surface-2", text: "text-ink-strong", dot: "bg-ink-faint" },
  Available: { bg: "bg-success-soft", text: "text-success", dot: "bg-success-solid" },
  Testing: { bg: "bg-info-soft", text: "text-info-strong", dot: "bg-info-solid" },
  Production: { bg: "bg-warning-soft", text: "text-warning", dot: "bg-warning-solid" },
  "Need Review": { bg: "bg-warning-soft-2", text: "text-warning", dot: "bg-warning-solid" },
  "Need Access": { bg: "bg-pink-soft", text: "text-pink", dot: "bg-pink-solid" },
  Failed: { bg: "bg-danger-soft", text: "text-danger", dot: "bg-danger-solid" },
  Archived: { bg: "bg-surface-2", text: "text-ink-faint-strong", dot: "bg-ink-faint" },
};

export const accessStyles: Record<string, { bg: string; text: string }> = {
  Public: { bg: "bg-success-soft", text: "text-success" },
  Private: { bg: "bg-purple-soft", text: "text-purple" },
  Gated: { bg: "bg-warning-soft-2", text: "text-warning" },
};

export const compatibilityStyles: Record<CompatibilityStatus, { bg: string; text: string }> = {
  "vLLM Compatible": { bg: "bg-success-soft", text: "text-success" },
  "Transformers Compatible": { bg: "bg-info-soft", text: "text-info-strong" },
  "Need Review": { bg: "bg-warning-soft-2", text: "text-warning" },
  "Not Supported": { bg: "bg-danger-soft", text: "text-danger" },
};

export const providerStyles: Record<string, { bg: string; text: string }> = {
  "Hugging Face": { bg: "bg-warning-soft", text: "text-warning" },
  Local: { bg: "bg-purple-soft", text: "text-purple" },
  OpenAI: { bg: "bg-success-soft", text: "text-success" },
  Anthropic: { bg: "bg-pink-soft", text: "text-pink" },
  Google: { bg: "bg-info-soft", text: "text-info-strong" },
  "Custom API": { bg: "bg-surface-2", text: "text-ink-strong" },
};

function defaultFiles(modelId: string): ModelFile[] {
  const now = "2025-12-10T10:00:00Z";
  return [
    {
      id: generateId("file"),
      modelId,
      fileName: "config.json",
      fileType: "Config",
      fileSize: "1.2 KB",
      isRequired: true,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/config.json`,
      checksum: "sha256:a1b2c3d4",
      downloadedAt: now,
    },
    {
      id: generateId("file"),
      modelId,
      fileName: "tokenizer.json",
      fileType: "Tokenizer",
      fileSize: "7.1 MB",
      isRequired: true,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/tokenizer.json`,
      checksum: "sha256:e5f6g7h8",
      downloadedAt: now,
    },
    {
      id: generateId("file"),
      modelId,
      fileName: "tokenizer_config.json",
      fileType: "Config",
      fileSize: "4.8 KB",
      isRequired: true,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/tokenizer_config.json`,
      checksum: "sha256:i9j0k1l2",
      downloadedAt: now,
    },
    {
      id: generateId("file"),
      modelId,
      fileName: "model.safetensors",
      fileType: "Weights",
      fileSize: "14.1 GB",
      isRequired: true,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/model.safetensors`,
      checksum: "sha256:m3n4o5p6",
      downloadedAt: now,
    },
    {
      id: generateId("file"),
      modelId,
      fileName: "generation_config.json",
      fileType: "Config",
      fileSize: "0.8 KB",
      isRequired: false,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/generation_config.json`,
      checksum: "sha256:q7r8s9t0",
      downloadedAt: now,
    },
    {
      id: generateId("file"),
      modelId,
      fileName: "README.md",
      fileType: "Documentation",
      fileSize: "12.4 KB",
      isRequired: false,
      downloadStatus: "Downloaded",
      storageLocation: `/models/${modelId}/README.md`,
      checksum: "sha256:u1v2w3x4",
      downloadedAt: now,
    },
  ];
}

function defaultAuditLogs(modelId: string, modelName: string): AuditLog[] {
  return [
    {
      id: generateId("audit"),
      modelId,
      action: "Model imported",
      actor: "Admin-NQR",
      timestamp: "2025-11-20T09:00:00Z",
      status: "Success",
      notes: `${modelName} registered from Hugging Face import.`,
    },
    {
      id: generateId("audit"),
      modelId,
      action: "Metadata updated",
      actor: "ML Engineer",
      timestamp: "2025-11-22T14:30:00Z",
      status: "Info",
      notes: "Updated tags and owner assignment.",
    },
    {
      id: generateId("audit"),
      modelId,
      action: "Compatibility checked",
      actor: "System",
      timestamp: "2025-11-22T14:35:00Z",
      status: "Success",
      notes: "Compatibility check completed.",
    },
    {
      id: generateId("audit"),
      modelId,
      action: "Test executed",
      actor: "AI Team",
      timestamp: "2025-11-25T11:00:00Z",
      status: "Success",
      notes: "Smoke test passed in Playground.",
    },
  ];
}

export const initialModels: RegistryModel[] = [
  {
    id: "model-001",
    modelName: "Qwen2.5 7B Instruct",
    provider: "Hugging Face",
    repoId: "Qwen/Qwen2.5-7B-Instruct",
    repoUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
    author: "Qwen",
    task: "Text Generation",
    libraryName: "transformers",
    modelFormat: "HF / Safetensors",
    parameterSize: "7B",
    contextLength: 32768,
    license: "Apache-2.0",
    language: ["English", "Chinese"],
    tags: ["llm", "instruct", "qwen2.5", "7b"],
    accessType: "Public",
    importMode: "Full Download",
    revision: "main",
    commitSha: "a1b2c3d4e5f6",
    localPath: "/models/model-001",
    totalModelSize: "14.2 GB",
    status: "Available",
    owner: "AI Team",
    compatibilityStatus: "vLLM Compatible",
    deploymentReadiness: "Ready",
    vllmCompatible: "Yes",
    transformersCompatible: "Yes",
    requiresTrustRemoteCode: false,
    quantization: null,
    minVramRequired: "16 GB",
    recommendedGpu: "NVIDIA A10G",
    gpuCountRequired: 1,
    supportsStreaming: true,
    supportsChatTemplate: true,
    createdAt: "2025-11-20T09:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
    huggingFaceSource: {
      repoId: "Qwen/Qwen2.5-7B-Instruct",
      repoUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
      author: "Qwen",
      branch: "main",
      commitSha: "a1b2c3d4e5f6",
      downloads: 1_240_000,
      likes: 892,
      lastModified: "2025-11-18T08:30:00Z",
      baseModel: null,
      datasetUsed: null,
      modelCardSummary:
        "Qwen2.5 is the latest series of Qwen large language models. The 7B Instruct variant is optimized for instruction following and general-purpose chat.",
      accessType: "Public",
      importMode: "Full Download",
    },
    files: defaultFiles("model-001"),
    compatibilityChecklist: {
      accessValid: true,
      licenseReviewed: true,
      configAvailable: true,
      tokenizerAvailable: true,
      modelFilesAvailable: true,
      vllmSupported: true,
      hardwareChecked: true,
    },
    deployment: {
      environment: "Staging",
      servingEngine: "vLLM",
      endpointUrl: "https://staging.llm-ops.internal/v1/models/qwen2.5-7b",
      gpuCluster: "gpu-cluster-staging-01",
      replica: 2,
      status: "Running",
      lastDeployment: "2025-11-28T16:00:00Z",
      rollbackVersion: "v1.0.0",
    },
    evaluation: {
      evaluationDataset: "internal-qa-v2",
      accuracy: 87.4,
      hallucinationRate: 4.2,
      safetyScore: 92.1,
      latencyMs: 142,
      costEstimate: "$0.002 / 1K tokens",
      lastEvaluationRun: "2025-11-30T10:00:00Z",
    },
    usage: {
      totalRequests: 45_820,
      successRate: 99.2,
      errorRate: 0.8,
      averageLatencyMs: 138,
      tokenUsage: 12_400_000,
      estimatedCost: "$248.00",
      gpuUtilization: 68.5,
      activeEndpoint: "https://staging.llm-ops.internal/v1/models/qwen2.5-7b",
    },
    auditLogs: [
      ...defaultAuditLogs("model-001", "Qwen2.5 7B Instruct"),
      {
        id: generateId("audit"),
        modelId: "model-001",
        action: "Deployed to staging",
        actor: "Admin-NQR",
        timestamp: "2025-11-28T16:00:00Z",
        status: "Success",
        notes: "Model is ready to deploy with vLLM.",
      },
    ],
  },
  {
    id: "model-002",
    modelName: "Llama 3.1 8B Instruct",
    provider: "Hugging Face",
    repoId: "meta-llama/Llama-3.1-8B-Instruct",
    repoUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    author: "Meta",
    task: "Chat",
    libraryName: "transformers",
    modelFormat: "HF / Safetensors",
    parameterSize: "8B",
    contextLength: 131072,
    license: "Custom",
    language: ["English"],
    tags: ["llama", "llama3", "instruct", "8b"],
    accessType: "Gated",
    importMode: "Metadata Only",
    revision: "main",
    commitSha: "f6e5d4c3b2a1",
    localPath: null,
    totalModelSize: "16.1 GB",
    status: "Need Access",
    owner: "ML Engineer",
    compatibilityStatus: "Need Review",
    deploymentReadiness: "Need Review",
    vllmCompatible: "Need Review",
    transformersCompatible: "Yes",
    requiresTrustRemoteCode: false,
    quantization: null,
    minVramRequired: "20 GB",
    recommendedGpu: "NVIDIA A100",
    gpuCountRequired: 1,
    supportsStreaming: true,
    supportsChatTemplate: true,
    createdAt: "2025-11-15T11:00:00Z",
    updatedAt: "2025-11-25T09:00:00Z",
    huggingFaceSource: {
      repoId: "meta-llama/Llama-3.1-8B-Instruct",
      repoUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
      author: "Meta",
      branch: "main",
      commitSha: "f6e5d4c3b2a1",
      downloads: 3_450_000,
      likes: 2100,
      lastModified: "2025-10-02T14:15:00Z",
      baseModel: "meta-llama/Llama-3.1-8B",
      datasetUsed: "Meta synthetic instruction data",
      modelCardSummary:
        "Llama 3.1 is an auto-regressive language model that uses an optimized transformer architecture. Gated access required from Hugging Face.",
      accessType: "Gated",
      importMode: "Metadata Only",
    },
    files: [],
    compatibilityChecklist: {
      accessValid: false,
      licenseReviewed: false,
      configAvailable: false,
      tokenizerAvailable: false,
      modelFilesAvailable: false,
      vllmSupported: false,
      hardwareChecked: false,
    },
    deployment: {
      environment: "Development",
      servingEngine: "vLLM",
      endpointUrl: "",
      gpuCluster: "",
      replica: 0,
      status: "Not Deployed",
      lastDeployment: null,
      rollbackVersion: null,
    },
    evaluation: {
      evaluationDataset: "—",
      accuracy: 0,
      hallucinationRate: 0,
      safetyScore: 0,
      latencyMs: 0,
      costEstimate: "—",
      lastEvaluationRun: null,
    },
    usage: {
      totalRequests: 0,
      successRate: 0,
      errorRate: 0,
      averageLatencyMs: 0,
      tokenUsage: 0,
      estimatedCost: "$0.00",
      gpuUtilization: 0,
      activeEndpoint: null,
    },
    auditLogs: [
      {
        id: generateId("audit"),
        modelId: "model-002",
        action: "Model imported",
        actor: "Admin-NQR",
        timestamp: "2025-11-15T11:00:00Z",
        status: "Warning",
        notes: "This model requires gated access from Hugging Face.",
      },
    ],
  },
  {
    id: "model-003",
    modelName: "BGE Large Embedding",
    provider: "Hugging Face",
    repoId: "BAAI/bge-large-en-v1.5",
    repoUrl: "https://huggingface.co/BAAI/bge-large-en-v1.5",
    author: "BAAI",
    task: "Embedding",
    libraryName: "sentence-transformers",
    modelFormat: "HF",
    parameterSize: "568M",
    contextLength: 512,
    license: "MIT",
    language: ["English"],
    tags: ["embedding", "retrieval", "bge"],
    accessType: "Public",
    importMode: "Full Download",
    revision: "main",
    commitSha: "bge123abc456",
    localPath: "/models/model-003",
    totalModelSize: "1.3 GB",
    status: "Available",
    owner: "Product Team",
    compatibilityStatus: "Transformers Compatible",
    deploymentReadiness: "Ready",
    vllmCompatible: "No",
    transformersCompatible: "Yes",
    requiresTrustRemoteCode: false,
    quantization: null,
    minVramRequired: "4 GB",
    recommendedGpu: "NVIDIA T4",
    gpuCountRequired: 1,
    supportsStreaming: false,
    supportsChatTemplate: false,
    createdAt: "2025-10-05T08:00:00Z",
    updatedAt: "2025-11-20T14:00:00Z",
    huggingFaceSource: {
      repoId: "BAAI/bge-large-en-v1.5",
      repoUrl: "https://huggingface.co/BAAI/bge-large-en-v1.5",
      author: "BAAI",
      branch: "main",
      commitSha: "bge123abc456",
      downloads: 890_000,
      likes: 456,
      lastModified: "2025-08-21T06:00:00Z",
      baseModel: null,
      datasetUsed: null,
      modelCardSummary: "BGE embedding model for dense retrieval and semantic search.",
      accessType: "Public",
      importMode: "Full Download",
    },
    files: defaultFiles("model-003").slice(0, 4),
    compatibilityChecklist: {
      accessValid: true,
      licenseReviewed: true,
      configAvailable: true,
      tokenizerAvailable: true,
      modelFilesAvailable: true,
      vllmSupported: false,
      hardwareChecked: true,
    },
    deployment: {
      environment: "Production",
      servingEngine: "Transformers",
      endpointUrl: "https://api.llm-ops.internal/v1/embeddings/bge-large",
      gpuCluster: "gpu-cluster-prod-02",
      replica: 3,
      status: "Running",
      lastDeployment: "2025-11-10T12:00:00Z",
      rollbackVersion: "v2.1.0",
    },
    evaluation: {
      evaluationDataset: "retrieval-benchmark-v1",
      accuracy: 91.8,
      hallucinationRate: 0,
      safetyScore: 98.5,
      latencyMs: 28,
      costEstimate: "$0.0001 / 1K tokens",
      lastEvaluationRun: "2025-11-18T09:00:00Z",
    },
    usage: {
      totalRequests: 128_400,
      successRate: 99.8,
      errorRate: 0.2,
      averageLatencyMs: 26,
      tokenUsage: 45_000_000,
      estimatedCost: "$45.00",
      gpuUtilization: 42.3,
      activeEndpoint: "https://api.llm-ops.internal/v1/embeddings/bge-large",
    },
    auditLogs: [
      ...defaultAuditLogs("model-003", "BGE Large Embedding"),
      {
        id: generateId("audit"),
        modelId: "model-003",
        action: "Promoted to production",
        actor: "Admin-NQR",
        timestamp: "2025-11-10T12:00:00Z",
        status: "Success",
        notes: "Production deployment approved after evaluation.",
      },
    ],
  },
  {
    id: "model-004",
    modelName: "Internal Invoice Assistant v2",
    provider: "Local",
    repoId: null,
    repoUrl: null,
    author: "Internal ML Team",
    task: "Chat",
    libraryName: "transformers",
    modelFormat: "LoRA Adapter",
    parameterSize: "7B",
    contextLength: 8192,
    license: "Internal",
    language: ["English", "Indonesian"],
    tags: ["invoice", "internal", "lora", "finance"],
    accessType: "Private",
    importMode: null,
    revision: "v2.0.0",
    commitSha: null,
    localPath: "/models/local/invoice-assistant-v2",
    totalModelSize: "420 MB",
    status: "Production",
    owner: "Product Team",
    compatibilityStatus: "vLLM Compatible",
    deploymentReadiness: "Ready",
    vllmCompatible: "Yes",
    transformersCompatible: "Yes",
    requiresTrustRemoteCode: false,
    quantization: "AWQ 4-bit",
    minVramRequired: "12 GB",
    recommendedGpu: "NVIDIA A10G",
    gpuCountRequired: 1,
    supportsStreaming: true,
    supportsChatTemplate: true,
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2025-12-05T16:30:00Z",
    huggingFaceSource: null,
    files: defaultFiles("model-004").slice(0, 3),
    compatibilityChecklist: {
      accessValid: true,
      licenseReviewed: true,
      configAvailable: true,
      tokenizerAvailable: true,
      modelFilesAvailable: true,
      vllmSupported: true,
      hardwareChecked: true,
    },
    deployment: {
      environment: "Production",
      servingEngine: "vLLM",
      endpointUrl: "https://api.llm-ops.internal/v1/models/invoice-assistant-v2",
      gpuCluster: "gpu-cluster-prod-01",
      replica: 4,
      status: "Running",
      lastDeployment: "2025-12-01T08:00:00Z",
      rollbackVersion: "v1.9.0",
    },
    evaluation: {
      evaluationDataset: "invoice-qa-internal",
      accuracy: 94.2,
      hallucinationRate: 2.1,
      safetyScore: 96.8,
      latencyMs: 98,
      costEstimate: "$0.0015 / 1K tokens",
      lastEvaluationRun: "2025-12-03T14:00:00Z",
    },
    usage: {
      totalRequests: 89_200,
      successRate: 99.5,
      errorRate: 0.5,
      averageLatencyMs: 95,
      tokenUsage: 28_600_000,
      estimatedCost: "$429.00",
      gpuUtilization: 74.2,
      activeEndpoint: "https://api.llm-ops.internal/v1/models/invoice-assistant-v2",
    },
    auditLogs: [
      ...defaultAuditLogs("model-004", "Internal Invoice Assistant v2"),
      {
        id: generateId("audit"),
        modelId: "model-004",
        action: "Promoted to production",
        actor: "Product Team",
        timestamp: "2025-10-15T10:00:00Z",
        status: "Success",
        notes: "Fine-tuned LoRA adapter deployed to production.",
      },
    ],
  },
  {
    id: "model-005",
    modelName: "GPT-4o Mini (API)",
    provider: "OpenAI",
    repoId: null,
    repoUrl: null,
    author: "OpenAI",
    task: "Chat",
    libraryName: "openai-api",
    modelFormat: "API",
    parameterSize: "—",
    contextLength: 128000,
    license: "Commercial",
    language: ["Multilingual"],
    tags: ["api", "openai", "chat"],
    accessType: "Private",
    importMode: null,
    revision: "latest",
    commitSha: null,
    localPath: null,
    totalModelSize: "—",
    status: "Testing",
    owner: "AI Team",
    compatibilityStatus: "Not Supported",
    deploymentReadiness: "Not Supported",
    vllmCompatible: "No",
    transformersCompatible: "No",
    requiresTrustRemoteCode: false,
    quantization: null,
    minVramRequired: "N/A (API)",
    recommendedGpu: "N/A",
    gpuCountRequired: 0,
    supportsStreaming: true,
    supportsChatTemplate: true,
    createdAt: "2025-11-01T08:00:00Z",
    updatedAt: "2025-11-28T12:00:00Z",
    huggingFaceSource: null,
    files: [],
    compatibilityChecklist: {
      accessValid: true,
      licenseReviewed: true,
      configAvailable: false,
      tokenizerAvailable: false,
      modelFilesAvailable: false,
      vllmSupported: false,
      hardwareChecked: true,
    },
    deployment: {
      environment: "Development",
      servingEngine: "Custom",
      endpointUrl: "https://api.openai.com/v1/chat/completions",
      gpuCluster: "N/A",
      replica: 0,
      status: "Not Deployed",
      lastDeployment: null,
      rollbackVersion: null,
    },
    evaluation: {
      evaluationDataset: "general-benchmark-v3",
      accuracy: 89.1,
      hallucinationRate: 3.8,
      safetyScore: 94.5,
      latencyMs: 320,
      costEstimate: "$0.15 / 1M input tokens",
      lastEvaluationRun: "2025-11-25T16:00:00Z",
    },
    usage: {
      totalRequests: 12_400,
      successRate: 98.9,
      errorRate: 1.1,
      averageLatencyMs: 315,
      tokenUsage: 8_200_000,
      estimatedCost: "$1,230.00",
      gpuUtilization: 0,
      activeEndpoint: null,
    },
    auditLogs: defaultAuditLogs("model-005", "GPT-4o Mini (API)"),
  },
  {
    id: "model-006",
    modelName: "Mistral 7B Instruct v0.3",
    provider: "Hugging Face",
    repoId: "mistralai/Mistral-7B-Instruct-v0.3",
    repoUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
    author: "Mistral AI",
    task: "Chat",
    libraryName: "transformers",
    modelFormat: "HF / Safetensors",
    parameterSize: "7B",
    contextLength: 32768,
    license: "Apache-2.0",
    language: ["English", "French", "German", "Spanish"],
    tags: ["mistral", "instruct", "7b"],
    accessType: "Public",
    importMode: "Full Download",
    revision: "main",
    commitSha: "mistral789xyz",
    localPath: "/models/model-006",
    totalModelSize: "14.0 GB",
    status: "Need Review",
    owner: "ML Engineer",
    compatibilityStatus: "Need Review",
    deploymentReadiness: "Need Review",
    vllmCompatible: "Need Review",
    transformersCompatible: "Yes",
    requiresTrustRemoteCode: false,
    quantization: null,
    minVramRequired: "16 GB",
    recommendedGpu: "NVIDIA A10G",
    gpuCountRequired: 1,
    supportsStreaming: true,
    supportsChatTemplate: true,
    createdAt: "2025-11-28T10:00:00Z",
    updatedAt: "2025-12-02T09:00:00Z",
    huggingFaceSource: {
      repoId: "mistralai/Mistral-7B-Instruct-v0.3",
      repoUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
      author: "Mistral AI",
      branch: "main",
      commitSha: "mistral789xyz",
      downloads: 2_100_000,
      likes: 1340,
      lastModified: "2025-09-14T11:45:00Z",
      baseModel: null,
      datasetUsed: null,
      modelCardSummary: "Mistral 7B Instruct v0.3 — pending compatibility review for vLLM deployment.",
      accessType: "Public",
      importMode: "Full Download",
    },
    files: defaultFiles("model-006"),
    compatibilityChecklist: {
      accessValid: true,
      licenseReviewed: true,
      configAvailable: true,
      tokenizerAvailable: true,
      modelFilesAvailable: true,
      vllmSupported: false,
      hardwareChecked: false,
    },
    deployment: {
      environment: "Development",
      servingEngine: "vLLM",
      endpointUrl: "",
      gpuCluster: "",
      replica: 0,
      status: "Not Deployed",
      lastDeployment: null,
      rollbackVersion: null,
    },
    evaluation: {
      evaluationDataset: "—",
      accuracy: 0,
      hallucinationRate: 0,
      safetyScore: 0,
      latencyMs: 0,
      costEstimate: "—",
      lastEvaluationRun: null,
    },
    usage: {
      totalRequests: 0,
      successRate: 0,
      errorRate: 0,
      averageLatencyMs: 0,
      tokenUsage: 0,
      estimatedCost: "$0.00",
      gpuUtilization: 0,
      activeEndpoint: null,
    },
    auditLogs: [
      ...defaultAuditLogs("model-006", "Mistral 7B Instruct v0.3"),
      {
        id: generateId("audit"),
        modelId: "model-006",
        action: "Compatibility checked",
        actor: "System",
        timestamp: "2025-12-02T09:00:00Z",
        status: "Warning",
        notes: "vLLM compatibility unknown — manual review required.",
      },
    ],
  },
];

export function computeSummaryStats(models: RegistryModel[]) {
  const active = models.filter((m) => m.status !== "Archived");
  return {
    total: active.length,
    readyToDeploy: active.filter(
      (m) => m.deploymentReadiness === "Ready" && m.status === "Available"
    ).length,
    needReview: active.filter(
      (m) => m.status === "Need Review" || m.compatibilityStatus === "Need Review"
    ).length,
    inProduction: active.filter((m) => m.status === "Production").length,
  };
}

export function filterModels(
  models: RegistryModel[],
  filters: import("@/modules/model-registry/types").ModelFilters
): RegistryModel[] {
  const q = filters.search.trim().toLowerCase();
  return models
    .filter((m) => m.status !== "Archived" || filters.status === "Archived")
    .filter((m) => {
      if (filters.provider !== "all" && m.provider !== filters.provider) return false;
      if (filters.task !== "all" && m.task !== filters.task) return false;
      if (filters.status !== "all" && m.status !== filters.status) return false;
      if (filters.access !== "all" && m.accessType !== filters.access) return false;
      if (filters.compatibility !== "all") {
        if (filters.compatibility === "vLLM Compatible" && m.compatibilityStatus !== "vLLM Compatible")
          return false;
        if (filters.compatibility === "Need Review" && m.compatibilityStatus !== "Need Review")
          return false;
        if (filters.compatibility === "Not Supported" && m.compatibilityStatus !== "Not Supported")
          return false;
      }
      if (!q) return true;
      const haystack = [
        m.modelName,
        m.repoId ?? "",
        m.provider,
        m.author,
        ...m.tags,
      ]
        .join(" ")
        .toLowerCase();
      return haystack.includes(q);
    })
    .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}
