#!/bin/bash
# Bootstrap a FRESH Transformer Lab backend so the app can talk to it.
#
# A fresh TL has an auto-created admin + personal team, but no API key — and the
# app's BFF needs `INFERENCE_API_KEY` (+ optionally `INFERENCE_TEAM_ID`) to call
# it. This mints them, then creates the experiments the app expects.
#
# Usage (TL must already be running):
#   bash scripts/bootstrap-tl-auth.sh
#   TL_URL=http://localhost:8340 bash scripts/bootstrap-tl-auth.sh
#
# The API key is written to a FILE (never echoed) — TL only ever returns the full
# key once, at creation, so re-running this mints a NEW key each time.
#
# IMPORTANT: the TL backend must run with TRANSFORMERLAB_JWT_SECRET and
# TRANSFORMERLAB_REFRESH_SECRET set. Without them TL still serves `/`, but every
# login 500s (jwt.encode gets None -> "TypeError: Expected a string value").
set -e

TL_URL="${TL_URL:-http://localhost:8339}"
TL_ADMIN_EMAIL="${TL_ADMIN_EMAIL:-admin@example.com}"
TL_ADMIN_PASSWORD="${TL_ADMIN_PASSWORD:-admin123}"
KEY_NAME="${KEY_NAME:-rantai-llmops}"
OUT_FILE="${OUT_FILE:-.env.tl-bootstrap}"
# Experiment names MUST match src/lib/tl-constants.ts (FINETUNE_EXPERIMENT).
FT_EXPERIMENT="${FT_EXPERIMENT:-rantai-ft}"
EVAL_EXPERIMENT="${EVAL_EXPERIMENT:-rantai-eval}"
QUOTA_MINUTES="${QUOTA_MINUTES:-5000000}"

echo "== 1) wait for TL at $TL_URL =="
curl -s --retry 60 --retry-delay 3 --retry-connrefused -m 200 -o /dev/null "$TL_URL/" \
  || { echo "❌ TL not reachable at $TL_URL"; exit 1; }
echo "   up"

echo "== 2) log in as $TL_ADMIN_EMAIL =="
TOKEN=$(curl -s -X POST "$TL_URL/auth/jwt/login" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  --data-urlencode "username=$TL_ADMIN_EMAIL" \
  --data-urlencode "password=$TL_ADMIN_PASSWORD" \
  | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')
if [ -z "$TOKEN" ]; then
  echo "❌ login failed. If TL returned a 500, its JWT secrets are unset —"
  echo "   start the backend with TRANSFORMERLAB_JWT_SECRET + TRANSFORMERLAB_REFRESH_SECRET."
  exit 1
fi
echo "   ok"

echo "== 3) resolve the admin's personal team =="
TEAM_ID=$(curl -s "$TL_URL/users/me/teams" -H "Authorization: Bearer $TOKEN" \
  | sed -n 's/.*"id":"\([^"]*\)".*/\1/p' | head -1)
[ -n "$TEAM_ID" ] || { echo "❌ could not resolve a team"; exit 1; }
echo "   team_id=$TEAM_ID"

echo "== 4) mint an API key ($KEY_NAME) =="
# NOTE: the full key lives in the `api_key` field and is returned ONLY here.
API_KEY=$(curl -s -X POST "$TL_URL/auth/api-keys" \
  -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d "{\"name\":\"$KEY_NAME\",\"team_id\":\"$TEAM_ID\"}" \
  | sed -n 's/.*"api_key":"\([^"]*\)".*/\1/p')
[ -n "$API_KEY" ] || { echo "❌ could not create an API key"; exit 1; }
echo "   created (${#API_KEY} chars)"

H=(-H "Authorization: Bearer $API_KEY" -H "X-Team-Id: $TEAM_ID")

echo "== 5) create experiments ($FT_EXPERIMENT, $EVAL_EXPERIMENT) =="
curl -s "${H[@]}" "$TL_URL/experiment/create?name=$FT_EXPERIMENT"   >/dev/null || true
curl -s "${H[@]}" "$TL_URL/experiment/create?name=$EVAL_EXPERIMENT" >/dev/null || true
echo "   ok"

echo "== 6) raise the self-host quota =="
curl -s -X PATCH "${H[@]}" -H "Content-Type: application/json" \
  "$TL_URL/quota/team/$TEAM_ID" -d "{\"monthly_quota_minutes\":$QUOTA_MINUTES}" >/dev/null || true
echo "   ok"

# Write, don't echo: the key must not land in a shell history / CI log.
umask 077
cat > "$OUT_FILE" <<EOF
# Generated by scripts/bootstrap-tl-auth.sh — paste into .env.local (or Portainer env).
INFERENCE_API_KEY=$API_KEY
INFERENCE_TEAM_ID=$TEAM_ID
EOF

echo ""
echo "✅ Done. Credentials written to: $OUT_FILE  (key starts ${API_KEY:0:6}…)"
echo "   Put INFERENCE_API_KEY + INFERENCE_TEAM_ID from that file into your env."
echo "   Re-running mints a NEW key — TL only returns the full key at creation."
